// Généré par scripts/generate-character-bank.mjs, fusion de deux sources :
// les 38 profils de langue embarqués (src-tauri/binaries/*.conf — tous les
// caractères qui y apparaissent comme variante, moins l'alphabet et les
// chiffres, déjà atteignables directement au clavier physique) et des jeux
// de symboles curés à la main (CURATED_SETS dans le script : indices,
// exposants, flèches, monnaies, mathématiques/logique étendus — rien de
// tout ça ne vient d'un .conf, donc pas de langue associée). Chaque entrée
// porte : les langues et/ou catégories qui la concernent, sa lettre de base
// si elle est décomposable via Unicode NFD (ex. "É" porte "E" — permet un
// filtre soustractif du type "Français" + "E" pour isoler "É"/"é"), et
// "Diacritic" si c'est une marque combinante isolée (même détection que
// isCombiningMark(), AccentHUD.tsx).
//
// Régénérer si de nouvelles langues/caractères sont ajoutés aux profils, ou
// si CURATED_SETS change : node scripts/generate-character-bank.mjs
export type BankChar = { char: string; flags: string[] };

export const CHARACTER_BANK: BankChar[] = [
  { char: "¢", flags: ["Currency"] },
  { char: "£", flags: ["Currency"] },
  { char: "¤", flags: ["Currency"] },
  { char: "¥", flags: ["Currency"] },
  { char: "¬", flags: ["Logic"] },
  { char: "°", flags: ["Math"] },
  { char: "±", flags: ["Math"] },
  { char: "²", flags: ["Superscript"] },
  { char: "³", flags: ["Superscript"] },
  { char: "¹", flags: ["Superscript"] },
  { char: "À", flags: ["Català","Français","Gàidhlig","Hausa","Italiano","Kreyòl ayisyen","Português","A"] },
  { char: "Á", flags: ["Avañe'ẽ","Español","Gaeilge","Hausa","Magyar","Português","Íslenska","Čeština","A"] },
  { char: "Â", flags: ["Français","Hausa","Português","Română","A"] },
  { char: "Ã", flags: ["Avañe'ẽ","Português","A"] },
  { char: "Ä", flags: ["Deutsch","Eesti","Lëtzebuergesch","Suomi","Svenska","A"] },
  { char: "Å", flags: ["Dansk","Norsk","Suomi","Svenska","A"] },
  { char: "Æ", flags: ["Dansk","Français","Norsk","Íslenska"] },
  { char: "Ç", flags: ["Azərbaycan dili","Català","Français","Português","Shqip","Türkçe","C"] },
  { char: "È", flags: ["Català","Français","Gàidhlig","Hausa","Italiano","Kreyòl ayisyen","E"] },
  { char: "É", flags: ["Avañe'ẽ","Català","Español","Français","Gaeilge","Hausa","Italiano","Lëtzebuergesch","Magyar","Português","Íslenska","Čeština","E"] },
  { char: "Ê", flags: ["Afrikaans","Français","Hausa","Português","E"] },
  { char: "Ë", flags: ["Afrikaans","Français","Lëtzebuergesch","Nederlands","Shqip","E"] },
  { char: "Ì", flags: ["Gàidhlig","Hausa","Italiano","I"] },
  { char: "Í", flags: ["Avañe'ẽ","Català","Español","Gaeilge","Hausa","Magyar","Português","Íslenska","Čeština","I"] },
  { char: "Î", flags: ["Afrikaans","Français","Hausa","Română","I"] },
  { char: "Ï", flags: ["Afrikaans","Català","Français","Nederlands","I"] },
  { char: "Ð", flags: ["Íslenska"] },
  { char: "Ñ", flags: ["Avañe'ẽ","Español","Euskara","N"] },
  { char: "Ò", flags: ["Català","Gàidhlig","Hausa","Italiano","Kreyòl ayisyen","O"] },
  { char: "Ó", flags: ["Avañe'ẽ","Català","Español","Gaeilge","Hausa","Magyar","Polski","Português","Íslenska","Čeština","O"] },
  { char: "Ô", flags: ["Afrikaans","Français","Hausa","Português","O"] },
  { char: "Õ", flags: ["Avañe'ẽ","Eesti","Português","O"] },
  { char: "Ö", flags: ["Afrikaans","Azərbaycan dili","Deutsch","Eesti","Magyar","Nederlands","Suomi","Svenska","Türkçe","Íslenska","O"] },
  { char: "×", flags: ["Math"] },
  { char: "Ø", flags: ["Dansk","Norsk"] },
  { char: "Ù", flags: ["Français","Gàidhlig","Hausa","Italiano","U"] },
  { char: "Ú", flags: ["Avañe'ẽ","Català","Español","Gaeilge","Hausa","Magyar","Português","Íslenska","Čeština","U"] },
  { char: "Û", flags: ["Afrikaans","Français","Hausa","U"] },
  { char: "Ü", flags: ["Afrikaans","Azərbaycan dili","Català","Deutsch","Eesti","Español","Français","Hànyǔ Pīnyīn","Magyar","Nederlands","Türkçe","U"] },
  { char: "Ý", flags: ["Avañe'ẽ","Íslenska","Čeština","Y"] },
  { char: "Þ", flags: ["Íslenska"] },
  { char: "ß", flags: ["Deutsch"] },
  { char: "à", flags: ["Català","Français","Gàidhlig","Hausa","Italiano","Kreyòl ayisyen","Português","A"] },
  { char: "á", flags: ["Avañe'ẽ","Español","Gaeilge","Hausa","Magyar","Português","Íslenska","Čeština","A"] },
  { char: "â", flags: ["Français","Hausa","Português","Română","A"] },
  { char: "ã", flags: ["Avañe'ẽ","Português","A"] },
  { char: "ä", flags: ["Deutsch","Eesti","Lëtzebuergesch","Suomi","Svenska","A"] },
  { char: "å", flags: ["Dansk","Norsk","Suomi","Svenska","A"] },
  { char: "æ", flags: ["Dansk","Français","Norsk","Íslenska"] },
  { char: "ç", flags: ["Azərbaycan dili","Català","Français","Português","Shqip","Türkçe","C"] },
  { char: "è", flags: ["Català","Français","Gàidhlig","Hausa","Italiano","Kreyòl ayisyen","E"] },
  { char: "é", flags: ["Avañe'ẽ","Català","Español","Français","Gaeilge","Hausa","Italiano","Lëtzebuergesch","Magyar","Português","Íslenska","Čeština","E"] },
  { char: "ê", flags: ["Afrikaans","Français","Hausa","Português","E"] },
  { char: "ë", flags: ["Afrikaans","Français","Lëtzebuergesch","Nederlands","Shqip","E"] },
  { char: "ì", flags: ["Gàidhlig","Hausa","Italiano","I"] },
  { char: "í", flags: ["Avañe'ẽ","Català","Español","Gaeilge","Hausa","Magyar","Português","Íslenska","Čeština","I"] },
  { char: "î", flags: ["Afrikaans","Français","Hausa","Română","I"] },
  { char: "ï", flags: ["Afrikaans","Català","Français","Nederlands","I"] },
  { char: "ð", flags: ["Íslenska"] },
  { char: "ñ", flags: ["Avañe'ẽ","Español","Euskara","N"] },
  { char: "ò", flags: ["Català","Gàidhlig","Hausa","Italiano","Kreyòl ayisyen","O"] },
  { char: "ó", flags: ["Avañe'ẽ","Català","Español","Gaeilge","Hausa","Magyar","Polski","Português","Íslenska","Čeština","O"] },
  { char: "ô", flags: ["Afrikaans","Français","Hausa","Português","O"] },
  { char: "õ", flags: ["Avañe'ẽ","Eesti","Português","O"] },
  { char: "ö", flags: ["Afrikaans","Azərbaycan dili","Deutsch","Eesti","Magyar","Nederlands","Suomi","Svenska","Türkçe","Íslenska","O"] },
  { char: "÷", flags: ["Math"] },
  { char: "ø", flags: ["Dansk","Norsk"] },
  { char: "ù", flags: ["Français","Gàidhlig","Hausa","Italiano","U"] },
  { char: "ú", flags: ["Avañe'ẽ","Català","Español","Gaeilge","Hausa","Magyar","Português","Íslenska","Čeština","U"] },
  { char: "û", flags: ["Afrikaans","Français","Hausa","U"] },
  { char: "ü", flags: ["Afrikaans","Azərbaycan dili","Català","Deutsch","Eesti","Español","Français","Hànyǔ Pīnyīn","Magyar","Nederlands","Türkçe","U"] },
  { char: "ý", flags: ["Avañe'ẽ","Íslenska","Čeština","Y"] },
  { char: "þ", flags: ["Íslenska"] },
  { char: "ÿ", flags: ["Français","Y"] },
  { char: "Ā", flags: ["Hausa","Latviešu","Reo Māori","A"] },
  { char: "ā", flags: ["Hausa","Latviešu","Reo Māori","A"] },
  { char: "Ă", flags: ["Română","A"] },
  { char: "ă", flags: ["Română","A"] },
  { char: "Ą", flags: ["Lietuvių","Polski","A"] },
  { char: "ą", flags: ["Lietuvių","Polski","A"] },
  { char: "Ć", flags: ["Hrvatski","Polski","Srpski","C"] },
  { char: "ć", flags: ["Hrvatski","Polski","Srpski","C"] },
  { char: "Č", flags: ["Hrvatski","Latviešu","Lietuvių","Srpski","Čeština","C"] },
  { char: "č", flags: ["Hrvatski","Latviešu","Lietuvių","Srpski","Čeština","C"] },
  { char: "Ď", flags: ["Čeština","D"] },
  { char: "ď", flags: ["Čeština","D"] },
  { char: "Đ", flags: ["Hrvatski","Srpski","Tiếng Việt"] },
  { char: "đ", flags: ["Hrvatski","Srpski","Tiếng Việt"] },
  { char: "Ē", flags: ["Hausa","Latviešu","Reo Māori","E"] },
  { char: "ē", flags: ["Hausa","Latviešu","Reo Māori","E"] },
  { char: "Ė", flags: ["Lietuvių","E"] },
  { char: "ė", flags: ["Lietuvių","E"] },
  { char: "Ę", flags: ["Lietuvių","Polski","E"] },
  { char: "ę", flags: ["Lietuvių","Polski","E"] },
  { char: "Ě", flags: ["Čeština","E"] },
  { char: "ě", flags: ["Čeština","E"] },
  { char: "Ğ", flags: ["Azərbaycan dili","Türkçe","G"] },
  { char: "ğ", flags: ["Azərbaycan dili","Türkçe","G"] },
  { char: "Ģ", flags: ["Latviešu","G"] },
  { char: "ģ", flags: ["Latviešu","G"] },
  { char: "Ĩ", flags: ["Avañe'ẽ","I"] },
  { char: "ĩ", flags: ["Avañe'ẽ","I"] },
  { char: "Ī", flags: ["Hausa","Latviešu","Reo Māori","I"] },
  { char: "ī", flags: ["Hausa","Latviešu","Reo Māori","I"] },
  { char: "Į", flags: ["Lietuvių","I"] },
  { char: "į", flags: ["Lietuvių","I"] },
  { char: "İ", flags: ["Azərbaycan dili","Türkçe","I"] },
  { char: "ı", flags: ["Azərbaycan dili","Türkçe"] },
  { char: "Ķ", flags: ["Latviešu","K"] },
  { char: "ķ", flags: ["Latviešu","K"] },
  { char: "Ļ", flags: ["Latviešu","L"] },
  { char: "ļ", flags: ["Latviešu","L"] },
  { char: "Ł", flags: ["Polski"] },
  { char: "ł", flags: ["Polski"] },
  { char: "Ń", flags: ["Polski","N"] },
  { char: "ń", flags: ["Polski","N"] },
  { char: "Ņ", flags: ["Latviešu","N"] },
  { char: "ņ", flags: ["Latviešu","N"] },
  { char: "Ň", flags: ["Čeština","N"] },
  { char: "ň", flags: ["Čeština","N"] },
  { char: "Ō", flags: ["Hausa","Reo Māori","O"] },
  { char: "ō", flags: ["Hausa","Reo Māori","O"] },
  { char: "Ő", flags: ["Magyar","O"] },
  { char: "ő", flags: ["Magyar","O"] },
  { char: "Œ", flags: ["Français"] },
  { char: "œ", flags: ["Français"] },
  { char: "Ř", flags: ["Čeština","R"] },
  { char: "ř", flags: ["Čeština","R"] },
  { char: "Ś", flags: ["Polski","S"] },
  { char: "ś", flags: ["Polski","S"] },
  { char: "Ş", flags: ["Azərbaycan dili","Türkçe","S"] },
  { char: "ş", flags: ["Azərbaycan dili","Türkçe","S"] },
  { char: "Š", flags: ["Hrvatski","Latviešu","Lietuvių","Srpski","Čeština","S"] },
  { char: "š", flags: ["Hrvatski","Latviešu","Lietuvių","Srpski","Čeština","S"] },
  { char: "Ť", flags: ["Čeština","T"] },
  { char: "ť", flags: ["Čeština","T"] },
  { char: "Ũ", flags: ["Avañe'ẽ","U"] },
  { char: "ũ", flags: ["Avañe'ẽ","U"] },
  { char: "Ū", flags: ["Hausa","Latviešu","Lietuvių","Reo Māori","U"] },
  { char: "ū", flags: ["Hausa","Latviešu","Lietuvių","Reo Māori","U"] },
  { char: "Ů", flags: ["Čeština","U"] },
  { char: "ů", flags: ["Čeština","U"] },
  { char: "Ű", flags: ["Magyar","U"] },
  { char: "ű", flags: ["Magyar","U"] },
  { char: "Ų", flags: ["Lietuvių","U"] },
  { char: "ų", flags: ["Lietuvių","U"] },
  { char: "Ÿ", flags: ["Français","Y"] },
  { char: "Ź", flags: ["Polski","Z"] },
  { char: "ź", flags: ["Polski","Z"] },
  { char: "Ż", flags: ["Polski","Z"] },
  { char: "ż", flags: ["Polski","Z"] },
  { char: "Ž", flags: ["Hrvatski","Latviešu","Lietuvių","Srpski","Čeština","Z"] },
  { char: "ž", flags: ["Hrvatski","Latviešu","Lietuvių","Srpski","Čeština","Z"] },
  { char: "Ɓ", flags: ["Hausa"] },
  { char: "Ɗ", flags: ["Hausa"] },
  { char: "Ə", flags: ["Azərbaycan dili"] },
  { char: "Ƙ", flags: ["Hausa"] },
  { char: "ƙ", flags: ["Hausa"] },
  { char: "Ƴ", flags: ["Hausa"] },
  { char: "ƴ", flags: ["Hausa"] },
  { char: "Ș", flags: ["Română","S"] },
  { char: "ș", flags: ["Română","S"] },
  { char: "Ț", flags: ["Română","T"] },
  { char: "ț", flags: ["Română","T"] },
  { char: "ɓ", flags: ["Hausa"] },
  { char: "ɗ", flags: ["Hausa"] },
  { char: "ə", flags: ["Azərbaycan dili"] },
  { char: "̀", flags: ["Català","Français","Gàidhlig","Hausa","Hànyǔ Pīnyīn","Italiano","Kreyòl ayisyen","Português","Tiếng Việt","Diacritic"] },
  { char: "́", flags: ["Avañe'ẽ","Català","Español","Français","Gaeilge","Hausa","Hrvatski","Hànyǔ Pīnyīn","Italiano","Lëtzebuergesch","Magyar","Polski","Português","Srpski","Tiếng Việt","Íslenska","Čeština","Diacritic"] },
  { char: "̂", flags: ["Afrikaans","Français","Hausa","Português","Română","Tiếng Việt","Diacritic"] },
  { char: "̃", flags: ["Avañe'ẽ","Eesti","Español","Euskara","Português","Tiếng Việt","Diacritic"] },
  { char: "̄", flags: ["Diacritic","Hausa","Hànyǔ Pīnyīn","Latviešu","Lietuvių","Reo Māori"] },
  { char: "̆", flags: ["Azərbaycan dili","Română","Tiếng Việt","Türkçe","Diacritic"] },
  { char: "̇", flags: ["Azərbaycan dili","Diacritic","Igbo","Lietuvių","Polski","Türkçe"] },
  { char: "̈", flags: ["Afrikaans","Azərbaycan dili","Català","Deutsch","Diacritic","Eesti","Español","Français","Lëtzebuergesch","Magyar","Nederlands","Shqip","Suomi","Svenska","Türkçe","Íslenska"] },
  { char: "̉", flags: ["Tiếng Việt","Diacritic"] },
  { char: "̊", flags: ["Dansk","Diacritic","Norsk","Suomi","Svenska","Čeština"] },
  { char: "̋", flags: ["Diacritic","Magyar"] },
  { char: "̌", flags: ["Diacritic","Hrvatski","Hànyǔ Pīnyīn","Latviešu","Lietuvių","Srpski","Čeština"] },
  { char: "̛", flags: ["Tiếng Việt","Diacritic"] },
  { char: "̣", flags: ["Igbo","Tiếng Việt","Yorùbá","Diacritic"] },
  { char: "̦", flags: ["Diacritic","Română"] },
  { char: "̧", flags: ["Azərbaycan dili","Català","Diacritic","Français","Latviešu","Português","Shqip","Türkçe"] },
  { char: "̨", flags: ["Diacritic","Lietuvių","Polski"] },
  { char: "Ṅ", flags: ["Igbo","N"] },
  { char: "ṅ", flags: ["Igbo","N"] },
  { char: "Ṣ", flags: ["Yorùbá","S"] },
  { char: "ṣ", flags: ["Yorùbá","S"] },
  { char: "ẞ", flags: ["Deutsch"] },
  { char: "Ẹ", flags: ["Yorùbá","E"] },
  { char: "ẹ", flags: ["Yorùbá","E"] },
  { char: "Ẽ", flags: ["Avañe'ẽ","E"] },
  { char: "ẽ", flags: ["Avañe'ẽ","E"] },
  { char: "Ị", flags: ["Igbo","I"] },
  { char: "ị", flags: ["Igbo","I"] },
  { char: "Ọ", flags: ["Igbo","Yorùbá","O"] },
  { char: "ọ", flags: ["Igbo","Yorùbá","O"] },
  { char: "Ụ", flags: ["Igbo","U"] },
  { char: "ụ", flags: ["Igbo","U"] },
  { char: "Ỹ", flags: ["Avañe'ẽ","Y"] },
  { char: "ỹ", flags: ["Avañe'ẽ","Y"] },
  { char: "′", flags: ["Math"] },
  { char: "″", flags: ["Math"] },
  { char: "⁰", flags: ["Superscript"] },
  { char: "⁴", flags: ["Superscript"] },
  { char: "⁵", flags: ["Superscript"] },
  { char: "⁶", flags: ["Superscript"] },
  { char: "⁷", flags: ["Superscript"] },
  { char: "⁸", flags: ["Superscript"] },
  { char: "⁹", flags: ["Superscript"] },
  { char: "⁺", flags: ["Superscript"] },
  { char: "⁻", flags: ["Superscript"] },
  { char: "⁼", flags: ["Superscript"] },
  { char: "⁽", flags: ["Superscript"] },
  { char: "⁾", flags: ["Superscript"] },
  { char: "ⁿ", flags: ["Superscript"] },
  { char: "₀", flags: ["Subscript"] },
  { char: "₁", flags: ["Subscript"] },
  { char: "₂", flags: ["Subscript"] },
  { char: "₃", flags: ["Subscript"] },
  { char: "₄", flags: ["Subscript"] },
  { char: "₅", flags: ["Subscript"] },
  { char: "₆", flags: ["Subscript"] },
  { char: "₇", flags: ["Subscript"] },
  { char: "₈", flags: ["Subscript"] },
  { char: "₉", flags: ["Subscript"] },
  { char: "₊", flags: ["Subscript"] },
  { char: "₋", flags: ["Subscript"] },
  { char: "₌", flags: ["Subscript"] },
  { char: "₍", flags: ["Subscript"] },
  { char: "₎", flags: ["Subscript"] },
  { char: "₠", flags: ["Currency"] },
  { char: "₡", flags: ["Currency"] },
  { char: "₦", flags: ["Currency"] },
  { char: "₨", flags: ["Currency"] },
  { char: "₩", flags: ["Currency"] },
  { char: "₪", flags: ["Currency"] },
  { char: "₫", flags: ["Currency"] },
  { char: "€", flags: ["Currency"] },
  { char: "₭", flags: ["Currency"] },
  { char: "₮", flags: ["Currency"] },
  { char: "₱", flags: ["Currency"] },
  { char: "₲", flags: ["Currency"] },
  { char: "₴", flags: ["Currency"] },
  { char: "₵", flags: ["Currency"] },
  { char: "₸", flags: ["Currency"] },
  { char: "₹", flags: ["Currency"] },
  { char: "₺", flags: ["Currency"] },
  { char: "₼", flags: ["Currency"] },
  { char: "₽", flags: ["Currency"] },
  { char: "₾", flags: ["Currency"] },
  { char: "₿", flags: ["Currency"] },
  { char: "←", flags: ["Arrow"] },
  { char: "↑", flags: ["Arrow"] },
  { char: "→", flags: ["Arrow"] },
  { char: "↓", flags: ["Arrow"] },
  { char: "↔", flags: ["Arrow"] },
  { char: "↕", flags: ["Arrow"] },
  { char: "↖", flags: ["Arrow"] },
  { char: "↗", flags: ["Arrow"] },
  { char: "↘", flags: ["Arrow"] },
  { char: "↙", flags: ["Arrow"] },
  { char: "↦", flags: ["Arrow"] },
  { char: "↩", flags: ["Arrow"] },
  { char: "↪", flags: ["Arrow"] },
  { char: "⇐", flags: ["Arrow"] },
  { char: "⇑", flags: ["Arrow"] },
  { char: "⇒", flags: ["Arrow","Logic"] },
  { char: "⇓", flags: ["Arrow"] },
  { char: "⇔", flags: ["Arrow","Logic"] },
  { char: "⇕", flags: ["Arrow"] },
  { char: "⇦", flags: ["Arrow"] },
  { char: "⇧", flags: ["Arrow"] },
  { char: "⇨", flags: ["Arrow"] },
  { char: "⇩", flags: ["Arrow"] },
  { char: "∀", flags: ["Logic"] },
  { char: "∂", flags: ["Math"] },
  { char: "∃", flags: ["Logic"] },
  { char: "∄", flags: ["Logic"] },
  { char: "∅", flags: ["Logic"] },
  { char: "∆", flags: ["Math"] },
  { char: "∇", flags: ["Math"] },
  { char: "∈", flags: ["Logic"] },
  { char: "∉", flags: ["Logic"] },
  { char: "∋", flags: ["Logic"] },
  { char: "∏", flags: ["Math"] },
  { char: "∑", flags: ["Math"] },
  { char: "√", flags: ["Math"] },
  { char: "∛", flags: ["Math"] },
  { char: "∜", flags: ["Math"] },
  { char: "∝", flags: ["Math"] },
  { char: "∞", flags: ["Math"] },
  { char: "∧", flags: ["Logic"] },
  { char: "∨", flags: ["Logic"] },
  { char: "∩", flags: ["Logic"] },
  { char: "∪", flags: ["Logic"] },
  { char: "∫", flags: ["Math"] },
  { char: "∬", flags: ["Math"] },
  { char: "∮", flags: ["Math"] },
  { char: "∴", flags: ["Math"] },
  { char: "∵", flags: ["Math"] },
  { char: "≈", flags: ["Math"] },
  { char: "≠", flags: ["Math"] },
  { char: "≡", flags: ["Math"] },
  { char: "≢", flags: ["Math"] },
  { char: "≤", flags: ["Math"] },
  { char: "≥", flags: ["Math"] },
  { char: "≪", flags: ["Math"] },
  { char: "≫", flags: ["Math"] },
  { char: "⊂", flags: ["Logic"] },
  { char: "⊃", flags: ["Logic"] },
  { char: "⊆", flags: ["Logic"] },
  { char: "⊇", flags: ["Logic"] },
  { char: "⊕", flags: ["Logic"] },
  { char: "⊢", flags: ["Logic"] },
  { char: "⊤", flags: ["Logic"] },
  { char: "⊥", flags: ["Logic"] },
  { char: "⊨", flags: ["Logic"] },
  { char: "⊻", flags: ["Logic"] },
  { char: "⌈", flags: ["Math"] },
  { char: "⌉", flags: ["Math"] },
  { char: "⌊", flags: ["Math"] },
  { char: "⌋", flags: ["Math"] },
];
