lang: Čeština
min:
a = á
c = č
d = ď
e = é, ě
i = í
n = ň
o = ó
r = ř
s = š
t = ť
u = ú, ů
y = ý
z = ž
1 = ◌́
2 = ◌̌
3 = ◌̊

maj:
a = Á
c = Č
d = Ď
e = É, Ě
i = Í
n = Ň
o = Ó
r = Ř
s = Š
t = Ť
u = Ú, Ů
y = Ý
z = Ž
