lang: Hausa
min:
a = ā, á, à, â
e = ē, é, è, ê
i = ī, í, ì, î
o = ō, ó, ò, ô
u = ū, ú, ù, û
b = ɓ
d = ɗ
k = ƙ
y = ƴ
1 = ◌̀
2 = ◌̂
3 = ◌̄
4 = ◌́

maj:
a = Ā, Á, À, Â
e = Ē, É, È, Ê
i = Ī, Í, Ì, Î
o = Ō, Ó, Ò, Ô
u = Ū, Ú, Ù, Û
b = Ɓ
d = Ɗ
k = Ƙ
y = Ƴ
